"""Types of the `mf` module of ModuForge Python modules (editor help only; not part of the module)."""
from typing import Any, Callable, Optional, Union

class Error(OSError): ...

id: str
name: str
version: str

def log(*values: Any) -> None: ...
def sleep(seconds: float) -> None: ...
def time() -> float: ...
def date(format: Optional[str] = None, time: Optional[float] = None) -> str: ...
def date_fields(time: Optional[float] = None, utc: bool = False) -> dict: ...
def granted(permission: str, target: Optional[str] = None) -> bool: ...
def request(permission: str, reason: str = "", target: Optional[str] = None) -> bool: ...
def notify(title: str, text: str = "") -> None: ...
def ask(question: str, secret: bool = False) -> Optional[str]: ...
def urlencode(text: str) -> str: ...
def random(count: int) -> bytes: ...

class Response:
    status: int
    body: str
    text: str
    headers: dict
    url: str
    def bytes(self) -> bytes: ...
    def json(self) -> Any: ...

def http(url: Union[str, dict], method: str = "GET", headers: Optional[dict] = None,
         body: Union[str, bytes, None] = None, form: Optional[dict] = None,
         files: Optional[list] = None, redirects: int = 5) -> Response: ...

class Connection:
    def read(self, max: int = 16384, timeout: Optional[float] = None) -> Optional[bytes]: ...
    def read_exactly(self, count: int, timeout: Optional[float] = None) -> Optional[bytes]: ...
    def read_line(self, timeout: Optional[float] = None) -> Optional[str]: ...
    def write(self, data: Union[str, bytes]) -> bool: ...
    def close(self) -> None: ...

def connect(host: str, port: int, tls: bool = False) -> Connection: ...

class WebSocket:
    def send(self, data: Union[str, bytes]) -> None: ...
    def receive(self, timeout: Optional[float] = None) -> Union[str, bytes, None]: ...
    def ping(self) -> None: ...
    def close(self) -> None: ...

def websocket(url: str, headers: Optional[dict] = None) -> WebSocket: ...

class storage:
    @staticmethod
    def read(path: str) -> Optional[str]: ...
    @staticmethod
    def read_bytes(path: str) -> Optional[bytes]: ...
    @staticmethod
    def write(path: str, data: Union[str, bytes]) -> bool: ...
    @staticmethod
    def delete(path: str) -> bool: ...
    @staticmethod
    def list() -> list: ...

class hash:
    @staticmethod
    def sha256(data: Union[str, bytes], raw: bool = False) -> Any: ...
    @staticmethod
    def md5(data: Union[str, bytes], raw: bool = False) -> Any: ...
    @staticmethod
    def sha1(data: Union[str, bytes], raw: bool = False) -> Any: ...
    @staticmethod
    def sha512(data: Union[str, bytes], raw: bool = False) -> Any: ...

class hmac:
    @staticmethod
    def sha256(key: Union[str, bytes], data: Union[str, bytes], raw: bool = False) -> Any: ...

class base64:
    @staticmethod
    def encode(data: Union[str, bytes], url: bool = False) -> str: ...
    @staticmethod
    def decode(text: str) -> bytes: ...

class hex:
    @staticmethod
    def encode(data: Union[str, bytes]) -> str: ...
    @staticmethod
    def decode(text: str) -> bytes: ...

class ui:
    @staticmethod
    def show(tree: Union[dict, list, str]) -> None: ...
    @staticmethod
    def wait(timeout: Optional[float] = None) -> Optional[dict]: ...
    @staticmethod
    def clear() -> None: ...

class apps:
    @staticmethod
    def list() -> list: ...
    @staticmethod
    def launch(app: str) -> dict: ...
    @staticmethod
    def open(url: str) -> None: ...
    @staticmethod
    def installed(package: str) -> bool: ...

class screen:
    @staticmethod
    def info() -> dict: ...
    @staticmethod
    def tap(x: int, y: int, ms: int = 50) -> None: ...
    @staticmethod
    def press(x: int, y: int, ms: int = 700) -> None: ...
    @staticmethod
    def swipe(x1: int, y1: int, x2: int, y2: int, ms: int = 300) -> None: ...
    @staticmethod
    def back() -> None: ...
    @staticmethod
    def home() -> None: ...
    @staticmethod
    def recents() -> None: ...
    @staticmethod
    def notifications() -> None: ...
    @staticmethod
    def texts() -> list: ...
    @staticmethod
    def find(text: str) -> list: ...
    @staticmethod
    def click(text: str) -> None: ...
    @staticmethod
    def type(text: str) -> None: ...
    @staticmethod
    def wait(text: str, timeout: float = 10) -> dict: ...
    @staticmethod
    def event(timeout: Optional[float] = None) -> Optional[dict]: ...

class camera:
    @staticmethod
    def list() -> list: ...
    @staticmethod
    def photo(path: str, lens: str = "back", size: int = 1280, quality: int = 85, flash: bool = False) -> dict: ...
